apiVersion: batch/v1
kind: Job
metadata:
  name: {{ randAlpha 8 }}
spec:
  template:
    spec:
      containers:
        - name: upgrade-sql-schema
          image: alpine:latest
          command: ["sleep", "5"]
      restartPolicy: Never
