apiVersion: batch/v1
kind: Job
metadata:
  generateName: upgrade-sql-schema
spec:
  template:
    spec:
      containers:
        - name: upgrade-sql-schema
          image: alpine:latest
          command: ["sleep", "5"]
      restartPolicy: Never
