apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app3
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "103"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: charts/sleep-app
    repoURL: https://github.com/w0wka91/k8s-argo.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
